### PR TITLE
fix: Fix data race when initializing logging

### LINKED ISSUE #1059: Race in `easy_logging.go` introduced in v1.8.0
1. What version of GO driver are you using?

v1.8.0 (v1.7.2 works)
   
2. What operating system and processor architecture are you using?

macOS 14.2.1, arm64
   
3. What version of GO are you using?

1.21.3, 1.22.0

4.Server version:* E.g. 1.90.1

N/A

5. What did you do?

Connected to Snowflake in more than one thread

6. What did you expect to see?

No data to be shared across the instances. Potentially shared data should be thread safe.

7. Can you set logging to DEBUG and collect the logs?

N/A
   
8. What is your Snowflake account identifier, if any? (Optional)

N/A

---

## Reproducible exampel

* Ensure you're using v1.8.0 -> `go get -u github.com/snowflakedb/gosnowflake@1.8.0`
* Run `go test . -race` with a `main_test.go` containing:

```go
package main

import (
	"database/sql"
	"sync"
	"testing"

	"github.com/snowflakedb/gosnowflake"
)

func TestMain(t *testing.T) {
	cfg := &gosnowflake.Config{
		Account:          "X",
		User:             "X",
		Password:         "X",
	}

	dsn, err := gosnowflake.DSN(cfg)
	if err != nil {
		panic(err)
	}

	n := 10
	wg := sync.WaitGroup{}
	wg.Add(n)

	for range make([]int, n) {
		go func() {
			defer wg.Done()

			db, err := sql.Open("snowflake", dsn)
			if err != nil {
				panic(err)
			}

			_ = db.Ping()
		}()
	}

	wg.Wait()
}
```

<details>
<summary>Output</summary>

```text
==================
WARNING: DATA RACE
Read at 0x0001042161e0 by goroutine 21:
  github.com/snowflakedb/gosnowflake.allowedToInitialize()
      /Users/simon/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.8.0/easy_logging.go:120 +0x30
  github.com/snowflakedb/gosnowflake.initEasyLogging()
      /Users/simon/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.8.0/easy_logging.go:41 +0x38
  github.com/snowflakedb/gosnowflake.buildSnowflakeConn()
      /Users/simon/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.8.0/connection.go:760 +0x2bc
  github.com/snowflakedb/gosnowflake.SnowflakeDriver.OpenWithConfig()
      /Users/simon/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.8.0/driver.go:38 +0x140
  github.com/snowflakedb/gosnowflake.SnowflakeDriver.Open()
      /Users/simon/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.8.0/driver.go:26 +0x13c
  github.com/snowflakedb/gosnowflake.(*SnowflakeDriver).Open()
      <autogenerated>:1 +0x44
  database/sql.dsnConnector.Connect()
      /usr/local/go/src/database/sql/sql.go:758 +0x5c
  database/sql.(*dsnConnector).Connect()
      <autogenerated>:1 +0x20
  database/sql.(*DB).conn()
      /usr/local/go/src/database/sql/sql.go:1387 +0x76c
  database/sql.(*DB).PingContext.func1()
      /usr/local/go/src/database/sql/sql.go:850 +0x5c
  database/sql.(*DB).retry()
      /usr/local/go/src/database/sql/sql.go:1538 +0x4c
  database/sql.(*DB).PingContext()
      /usr/local/go/src/database/sql/sql.go:849 +0x7c
  database/sql.(*DB).Ping()
      /usr/local/go/src/database/sql/sql.go:867 +0x9c
  x.TestMain.func1()
      /Users/simon/tmp/test-go/racy-snowflake/main_test.go:36 +0x88

Previous write at 0x0001042161e0 by goroutine 27:
  github.com/snowflakedb/gosnowflake.(*initTrials).setInitTrial()
      /Users/simon/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.8.0/easy_logging.go:26 +0x8ec
  github.com/snowflakedb/gosnowflake.initEasyLogging()
      /Users/simon/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.8.0/easy_logging.go:53 +0x8e0
  github.com/snowflakedb/gosnowflake.buildSnowflakeConn()
      /Users/simon/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.8.0/connection.go:760 +0x2bc
  github.com/snowflakedb/gosnowflake.SnowflakeDriver.OpenWithConfig()
      /Users/simon/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.8.0/driver.go:38 +0x140
  github.com/snowflakedb/gosnowflake.SnowflakeDriver.Open()
      /Users/simon/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.8.0/driver.go:26 +0x13c
  github.com/snowflakedb/gosnowflake.(*SnowflakeDriver).Open()
      <autogenerated>:1 +0x44
  database/sql.dsnConnector.Connect()
      /usr/local/go/src/database/sql/sql.go:758 +0x5c
  database/sql.(*dsnConnector).Connect()
      <autogenerated>:1 +0x20
  database/sql.(*DB).conn()
      /usr/local/go/src/database/sql/sql.go:1387 +0x76c
  database/sql.(*DB).PingContext.func1()
      /usr/local/go/src/database/sql/sql.go:850 +0x5c
  database/sql.(*DB).retry()
      /usr/local/go/src/database/sql/sql.go:1538 +0x4c
  database/sql.(*DB).PingContext()
      /usr/local/go/src/database/sql/sql.go:849 +0x7c
  database/sql.(*DB).Ping()
      /usr/local/go/src/database/sql/sql.go:867 +0x9c
  x.TestMain.func1()
      /Users/simon/tmp/test-go/racy-snowflake/main_test.go:36 +0x88

Goroutine 21 (running) created at:
  x.TestMain()
      /Users/simon/tmp/test-go/racy-snowflake/main_test.go:28 +0xc4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x194
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x40

Goroutine 27 (running) created at:
  x.TestMain()
      /Users/simon/tmp/test-go/racy-snowflake/main_test.go:28 +0xc4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x194
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x40
==================
```
</details>

## Root cause

The public shared variable here: https://github.com/snowflakedb/gosnowflake/blob/95345201ecd83fbbbb435f2bc653800b151e862e/easy_logging.go#L19-L23

Is read from without any mutex here: https://github.com/snowflakedb/gosnowflake/blob/95345201ecd83fbbbb435f2bc653800b151e862e/easy_logging.go#L120

Is written to without any mutex here: https://github.com/snowflakedb/gosnowflake/blob/95345201ecd83fbbbb435f2bc653800b151e862e/easy_logging.go#L26

Somewhat related to #616 and another reason to drop logging from the library and leave that to the caller.

### PR DESCRIPTION
**Pull request by bombsimon**
### Description

Add mutex to `initTrials` to avoid data race. Resolves #1059 

### Checklist
- [x] Code compiles correctly
- [ ] Run ``make fmt`` to fix inconsistent formats
  - Not run: ``make[1]: *** No rule to make target `fmt'.  Stop.``
- [ ] Run ``make lint`` to get lint errors and fix all of them
  - Not run: import errors and does not work on `master`
- [x] Created tests which fail without the change (if possible)
  - Creted a test but can't run it since test files have dependencies on other test files with `init` functions that requires me to connect to a real database. I tried to isolate it but had no success. Hopefully a pipeline can confirm the test or I can remove it if it's irrelevant.
- [ ] All tests passing
  - Can't get tests to pass, require account setup, also failing on `master`
- [ ] Extended the README / documentation, if necessary
  - Not necessary

### CODE REVIEW

**Comment by bombsimon** [comment]
Sadly I wont't be able to get back to you about the CLA until next week Monday but maybe that's fine. I'll sign it as soon as everything is sorted next week! Thanks for the quick response in the ticket!

**Comment by bombsimon** [comment]
I haven't forgotten this, I just haven't gotten the response I was expected yet. I'll let you know as soon as I do.

**Comment by bombsimon** [comment]
I have read the CLA Document and I hereby sign the CLA

File: easy_logging.go [hunk 1]
```diff
@@ -117,6 +129,9 @@ func createLogWriter(logPath string) (io.Writer, *os.File, error) {
 }
 
 func allowedToInitialize(clientConfigFileInput string) bool {
+	easyLoggingInitTrials.mu.RLock()
```
Comment (sfc-gh-knozderko) [inline easy_logging.go:132]: maybe let's lock only in initEasyLogging and reset, and remove locking from allowedToInitialize, setInitTrial, increaseReconfigureCounter. Otherwise many initialisations at the same time are still possible.

**Review by sfc-gh-knozderko — CHANGES_REQUESTED** [review]

File: easy_logging.go (hunk 1 above)
Comment (bombsimon) [reply easy_logging.go:132]: Hmm, I don't see how that solves the issue if we're allowed to write to it in any of `setInitTrial` or `increaseReconfigureCounter` and read from it in `allowedToInitialize`. Since the variable is global it can be read or written at the same time at any point.

If I remove locking from `allowedToInitialize`, `setInitTrial` and `increaseReconfigureCounter` I get a race in these methods. Running the reproducible example in the ticket:

```text
› go test . -race 
==================
WARNING: DATA RACE
Write at 0x0001021668c0 by goroutine 20:
  github.com/snowflakedb/gosnowflake.(*initTrials).setInitTrial()
[SNIP]
Previous read at 0x0001021668c0 by goroutine 21:
  github.com/snowflakedb/gosnowflake.allowedToInitialize()

==================
WARNING: DATA RACE
Write at 0x0001021668c8 by goroutine 26:
  github.com/snowflakedb/gosnowflake.(*initTrials).setInitTrial()
[SNIP]
Previous write at 0x0001021668c8 by goroutine 19:
  github.com/snowflakedb/gosnowflake.(*initTrials).setInitTrial()
```

I opted to use a `RWLock` so we can have multiple reads in `allowedToInitialize` at the same time and avoid unnecessary locking there.

Comment (bombsimon) [reply easy_logging.go:132]: Ah, never mind, now I see what you mean, you want me to take a lock through the whole `initEasyLogging`? I can do that, but that would introduce a new race if someone calls `setInitTrial`, `increaseReconfigureCounter` or `allowedToInitialize` outside of those methods.

It's also a bit weird to take the lock far away from where we do the write in my opinion but maybe that's just personal preference. Also this means that I'll have to take a full lock (read and write) even when a short read lock would be sufficient in `allowedToInitialize`.

Comment (bombsimon) [reply easy_logging.go]: Pushed a change with your suggested changes since where to lock is up to you. A bigger rewrite to leverage something like a `sync.Once` should probably be made in a separate PR and not as a part of this bug fix.

**Review by sfc-gh-knozderko — APPROVED** [review]

**Comment by sfc-gh-pfus** [comment]
Hi @bombsimon ! Thanks for your input, I merged your PR :)
