### PR TITLE
fix(config): derive account from host in FillMissingConfigParameters

### LINKED ISSUE #1432: SNOW-2135301: Connection fails when Host is provided but Account is not
1. What version of GO driver are you using?
1.14.1
   
2. What operating system and processor architecture are you using?
macOS 15.3.1, ARM64
   
3. What version of GO are you using?
1.24.1

4. Server version: 
9.14.2

5. What did you do?

Try to connect by initializing a Connector using Config instead of DSN:

```go
	ctor := gosnowflake.NewConnector(gosnowflake.SnowflakeDriver{}, gosnowflake.Config{
		Host:     "<account>.snowflakecomputing.com",
		Port:     443,
		User:     "<user>",
		Password: "<pwd>",
		Database: "<db>",
	})

	_, err := ctor.Connect(ctx)
	if err != nil {
		return fmt.Errorf("failed to connect to Snowflake: %w", err)
	}
```

6. What did you expect to see?

Expected to be able to connect since the account identifier can be implied from the Host, but received the following error instead:
`failed to connect to Snowflake: 260000: account is empty` 

Can't the driver parse the account from the host similarly to how it's done in `ParseDSN`?
https://github.com/snowflakedb/gosnowflake/blob/a1a961dfdcbe7e4898bbb9a414cdd055f98146b4/dsn.go#L427-L430

7. Can you set logging to DEBUG and collect the logs?

   N/A

### PR DESCRIPTION
**Pull request by d-padmanabhan**
### Description

SNOW-XXX (replace if applicable; community context: fixes https://github.com/snowflakedb/gosnowflake/issues/1432)

Programmatic `Config` with a full Snowflake `Host` and empty `Account` worked when built through `ParseDSN`, but `database/sql.Connector` paths call `FillMissingConfigParameters` without that earlier step, so `Account` stayed empty and connect failed with the empty-account error.

This change derives `Account` from the first DNS label of `Host` when `Account` is blank and `Host` matches the existing Snowflake hostname heuristic (`hostIncludesTopLevelDomain`), at the start of `FillMissingConfigParameters`. Dotted-account truncation from DSN query parameters remains in `ParseDSN` only; non-empty programmatic `Account` values are unchanged.

`doc.go` documents that split, fixes a few typos, corrects the `NewConnector` example variable name, and fixes the proxy parameter table row to `noProxy`. Tests cover US-style host, China region host, and a non-Snowflake internal hostname that still requires an explicit `Account`.

### Checklist

- [ ] Added proper logging (if possible) (not applicable)
- [x] Created tests which fail without the change (if possible)
- [x] Extended the README / documentation, if necessary (`doc.go` package documentation)

### CODE REVIEW

**Comment by d-padmanabhan** [comment]
I have read the CLA Document and I hereby sign the CLA

File: doc.go [hunk 1]
```diff
@@ -224,8 +224,8 @@ Alternatively, use OpenWithConfig() function to create a database handle with th
```
Comment (sfc-gh-pfus) [inline doc.go:224]: This looks good, thank you! One thing only - can you add an entry in changelog.md?

Comment (d-padmanabhan) [reply doc.go:224]: Added a `CHANGELOG.md` entry under Upcoming release; PTAL

File: CHANGELOG.md [hunk 2]
```diff
@@ -2,6 +2,10 @@
 
 ## Upcoming release
 
+Bug fixes:
+
+- Fixed empty `Account` when connecting with programmatic `Config` and `database/sql.Connector` by deriving `Account` from the first DNS label of `Host` in `FillMissingConfigParameters` when `Host` matches the Snowflake hostname pattern (snowflakedb/gosnowflake#1432).
```
Comment (sfc-gh-pfus) [inline CHANGELOG.md]: Can you fix the PR number?

Comment (d-padmanabhan) [reply CHANGELOG.md]: Sorry about that. I had pointed the changelog at the issue (#1432) instead of this PR (#1772). I have updated it and pushed the fix.

**Review by sfc-gh-pfus — APPROVED** [review]

**Comment by sfc-gh-pfus** [comment]
Hi @d-padmanabhan , thanks for your fix, it is now merged!
